-- require("codecompanion").setup({
--   adapters = {
--     http = {
--       openai = {
--         env = { api_key = os.getenv("OPENAI_API_KEY") },
--         schema = { model = { default = "gpt-4o-mini" } },
--       },
--     },
--   },
--   strategies = {
--     chat = {
--       adapter = "openai",
--       roles = { user = "User", assistant = "AI" },
--     },
--     inline = { adapter = "openai" },
--   },
-- })
